config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :categories, only: %i[index new create] do
      resources :spends, only: [:index] # as the requirement transaction are list for a given category
    end
    resources :spends, only: %i[new create] # as the requirement there is no show for a single transaction
  end
  # Defines the root path route ("/")
  root 'users#index'
end

app/models/spend.rb
class Spend < ApplicationRecord
  belongs_to :user
  has_many :category_spends
  has_many :categories, through: :category_spends

  validates :name, presence: true
  validates :amount, presence: true, comparison: { greater_than: 0 }

  def formatted_date
    Date.parse(created_at.to_s)
  end
end

app/controllers/spends_controller.rb
class SpendsController < ApplicationController
  before_action :authenticate_user!
  def index
    @category = Category.find params[:category_id]
    redirect_to users_path unless can? :read, @category

    @transactions = @category.spends.order(created_at: :DESC)
  end

  def new
    @new_transaction = Spend.new
    @categories = current_user.categories.order(created_at: :DESC)
  end

  def create
    par = transaction_params
    puts 'params are'
    unless params[:category]
      redirect_to new_user_spend_path(user_id: current_user), notice: 'you have to set atleast one category'
      return
    end
    spend = Spend.new(name: par[:name], amount: par[:amount], user: current_user)
    if spend.save
      params[:category][:selects].each do |id|
        CategorySpend.create(spend:, category: Category.find(id))
      end
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def transaction_params
    params.require(:spend).permit(:name, :amount)
  end
end

app/helpers/spends_helper.rb
module SpendsHelper
end

app/views/spends/index.html.erb
<div class="home-page">
  <div class="banner">
  <h3 class="left"><%= @category.name%></h3>
  <div class="right">$<%= @category.total_spend%></div>
</div>
<% if !@transactions.empty? %>
 <title class="heading">This are list of your categories</title>

 <% @transactions.each do |transaction| %>
 <div class="list-card">
  <div class="left"><div class="heading"><%= transaction.name%></div></div>
  <div class="sub-topic"><%= transaction.formatted_date%></div>
  <div class="right"><div class="content"></div>$<%= transaction.amount%></div>
 </div>
 <% end %>
  <% else %>
 <title class="heading">You have no categories, Pleas add one</title>
<% end %>

<%= button_to 'Add new transaction', new_user_spend_path(user_id: current_user), method: :get, class: "full success" %>

<%= render :partial => '/users/home' %>
</div>

app/views/spends/new.html.erb
<div class="home-page">
  <div class="banner">
  <h3>Register new transaction</h3>
</div>

<%= form_with model: @new_transaction, url: user_spends_path(:user_id => current_user)  do |form| %>
  <%= form.label :name, "Transaction name"%>
  <%= form.text_field :name , required: true%>
  <%= form.label :amount, "Spend on/amount" %>
  <%= form.number_field :amount , required: true%>
  <div class="checkbox-list">
    <h3>Select your categories</h3>
  <% @categories.each do |category| %>
  <div class="checkbox-with-label">
    <%= check_box('category', "selects",{:multiple => true}, category.id, nil)%>
  <%= form.label :category, category.name %><br/>
  </div>
  <% end %>
  </div>
  <%= form.submit class: "full success"%>
<% end %>

<%= render :partial => '/users/home' %>
</div>