config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :categories, only: %i[index new create] do
      resources :spends, only: [:index] # as the requirement transaction are list for a given category
    end
    resources :spends, only: %i[new create] # as the requirement there is no show for a single transaction
  end
  # Defines the root path route ("/")
  root 'users#index'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_spends
  has_many :spends, through: :category_spends

  validates :name, presence: true

  def total_spend
    spends.reduce(0) { |sum, spend| sum + spend.amount }
  end

  def formatted_date
    Date.parse(created_at.to_s)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = current_user.categories.order(created_at: :DESC)
  end

  def new
    @new_category = Category.new
  end

  def create
    par = strong_category
    new_category = Category.new(user: current_user, name: par[:name], icon: par[:icon])
    if new_category.save
      redirect_to users_path
    else
      render :new
    end
  end

  private

  # strong params
  def strong_category
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="home-page categories">
  <% if !@categories.empty? %>
  <div class="banner">
 <h3 class="sub-title">This are list of your categories</h3>
</div>
 <% @categories.each do |category| %>
 <%= link_to user_category_spends_path(:category_id => category), class: "list-card", method: :get  do%>
  <div class="img"><img src="<%= category.icon%>" alt="<%= category.name%>"/></div>
  <div class="mid"><div class="heading">
    <%= category.name%></div><div class="sub-topic"><%= category.formatted_date%>
    </div></div>
  <div class="right"><div class="content"></div>$<%= category.total_spend%></div>
 <%end%>
 <% end %>
  <% else %>
 <h3 class="sub-title">You have no categories, Pleas add one</h3>
<% end %>

<%= button_to 'Add new category', new_user_category_path, method: :get,class: "full success"  %>
<%= button_to 'logout', destroy_user_session_path, method: :delete, class: "full danger"  %>
</div>

app/views/categories/new.html.erb
<h1>Create new category</h1>
<%= form_with model: @new_category, url: user_categories_path(:user_id => current_user)  do |form| %>
  <%= form.label :name, "Category name"%>
  <%= form.text_field :name , required: true%>
  <%= form.label :icon, "Icon for this category" %>
  <%= form.text_field :icon , required: true%>
  <%= form.submit class: "full success" %>
<% end %>
<%= render :partial => '/users/home' %>